[[plugins]]
repo = 'Shougo/dein.vim'

# editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# ctrlp
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_source = '''
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

# tcomment_vim
[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source ~/.vim/rc/plugins/airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_source = 'nmap ga <Plug>(EasyAlign)'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
